### PR TITLE
moved Legend at the bottom of chart

### PR DESCRIPTION
**Pull request by ggepenyan**

### CODE REVIEW

**Comment by vonbearshark** [comment]
Thanks for submitting a PR!

It looks like you made your edits in lib/dist? That is where the generated code goes from the `build` commands. You'll want to make the edits in `src` so that the build commands output the new code into the dist

maybe I am missing something though

**Comment by ggepenyan** [comment]
I tried to make the changes in src but it didn't show my changes. That's why I did it that way

**Comment by ggepenyan** [comment]
Am I incorrect? Thank for responding )

**Comment by vonbearshark** [comment]
You need to run `npm build` to see the changes

**Comment by ggepenyan** [comment]
I have already sent the modified l"pull-request" files. Is it possible for you to check my changes without "npm build". It worked for me, so we could add a prop called for example "legendAtBottom" and if that set my code could work.

**Comment by ggepenyan** [comment]
Thanks

**Comment by vonbearshark** [comment]
I was able to check the changes, and they do look good. But we need to integrate them into the build system as-is. I can't publish it with the code altered like it is. It needs to be changes in the source

**Comment by ggepenyan** [comment]
So what do I have to do?

**Comment by vonbearshark** [comment]
You need to make the changes in the non-`dist` versions of the file, in the `src` files instead. So make the same changes in the `lib/src/Arcs.js` file rather than the `lib/dist/Arcs.js` file, and so on for all the changes. Then you can build the source changes with `babel lib/src --out-dir lib/dist`. Does that make sense?

**Comment by vonbearshark** [comment]
I am closing this PR, but I would be happy to continue to chat about it.

After reviewing the code, it looks like you can achieve what you intend via CSS/class selectors as-is anyway, so these changes shouldn't be needed

**Comment by vonbearshark** [comment]
I am closing this PR, but I would be happy to continue to chat about it.

After reviewing the code, it looks like you can achieve what you intend via CSS/class selectors as-is anyway, so these changes shouldn't be needed

**Pull request closed without merging**
